setwd("/home/abc/analytics/dynamic stock")
Boeing=read.csv("BoeingStock.csv")
CocaCola=read.csv("CocaColaStock.csv")
GE=read.csv("GEStock.csv")
IBMStock=read.csv("IBMStock.csv")
IBM=read.csv("IBMStock.csv")
rm(IBMStock)
Procter=read.csv("ProcterGambleStock.csv")
str(Boeing)
Boeing$Date[1]
Boeing$Date=as.Date(Boeing$Date,"%m/%d/%y")
 IBM$Date=as.Date(IBM$Date,"%m/%d/%y")
 Procter$Date=as.Date(Procter$Date,"%m/%d/%y")
 CocaCola$Date=as.Date(CocaCola$Date,"%m/%d/%y")
 GE$Date=as.Date(GE$Date,"%m/%d/%y")
 min(GE$Date)
 max(CocaCola$Date,na.rm = TRUE)
  ## PLOTTING DIFFERENT DATA VALUES OF STOCK OVER A PERIOD OF TIME
 plot(CocaCola$Date,CocaCola$StockPrice)
 lines(Procter$Date,Procter$StockPrice,color="red")